### ISSUE TITLE
Wrong HighPriorityIssueNotAssigned output format. It needs a blank space between the message and level

### ISSUE THREAD

**Issue by yersan** [jboss-set/bug-clerk#102]
See for example: 
https://issues.jboss.org/browse/JBEAP-6961?focusedCommentId=13524361&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13524361

**Comment by rpelisse** [comment]
Fixed will be released in 1.0.3 and in 1.1.0.
