### ISSUE TITLE
Allow BZ to be ignored for certain checks

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#15]
For instance, if there is no PR to be associated to a BZ, it would nice to be able to simply add a specific comment (ex: BugClerk#NoPR) to give a hint to BugClerk that it should not report the issue.

**Comment by xstefank** [comment]
[implemented](https://github.com/jboss-set/bug-clerk/commit/fd754244f713072ceeaffac25b653d271acf780d) - released with 0.6.0.Final

**Comment by rpelisse** [comment]
thanks !
