### ISSUE TITLE
Check Request #15: Regression detected on One-Off release to the original BZ

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#18]
Like [BZ1217239](https://bugzilla.redhat.com/show_bug.cgi?id=1217239).

**Comment by wolfc** [comment]
Bugclerk should look through the 'Blocks' list to find a potential one-off to analyse. It should not be a requirement that the one-off is cloned from the original BZ.

**Comment by rpelisse** [comment]
OK, so here is how I see the implementation of the check:
* if the BZ is a "Support Patch" and is Blocking BZ, and no Comments feature the word Regression, it will be consider for further analysis
* if, at least, one of the BZ being Blocks is featuring in the Comments the word Regression, it would be tagged as a potential issue (or missed regression).

Question is, does it make sense to do it the other way around also ? Meaning, should we check a BZ  not being a "one off" but depending on a one-off BZ having the word regression in its comments ?

**Comment by rpelisse** [comment]
OK, this is now [implemented](https://github.com/jboss-set/bug-clerk/blob/master/src/main/resources/org/jboss/jbossset/bugclerk/RegressionMayImpactOneOffRelease.drl) - and wil be released with 0.6.4.

Note that I opted to make this check an ERROR (not a WARNING), which means it will be reported on the BZ if spot. Given the  state of the rule, there is margin for False+, but given the conditions required for the message to be reported, I don't think it can "overflowed" BZ with useless comments...
