### ISSUE TITLE
Check Request #3: A BZ must never be proposed for multiple releases

### ISSUE THREAD

**Issue by wolfc** [jboss-set/bug-clerk#3]
In https://bugzilla.redhat.com/show_bug.cgi?id=1174152#c1 the bot approved the BZ for 6.3.z CP, while the BZ was actually a feature request.

**Comment by rpelisse** [comment]
First impl. commited: https://github.com/jboss-set/bug-clerk/commit/a18779b30056ff78308c8fd4a088093883ac3609
