### ISSUE TITLE
disable some rule checking as per issue state

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/bug-clerk#37]
I would recommend bug-clerk to disable some rule checking for VERIFIED valid issue, or CLOSED invalid issue (such as duplicate or not a bug)
see https://bugzilla.redhat.com/show_bug.cgi?id=1172830#c10

**Comment by rpelisse** [comment]
@soul2zimate  Actually, BugClerk already filtered issues that are CLOSED and it probably should do the same for verified. I'm going to implement that right away.

**Comment by rpelisse** [comment]
Implemented (see commit https://github.com/jboss-set/bug-clerk/commit/c9d7f04dc5578d36f9d1c818521fa732967528a5) and will be released with 0.9.0.
