### ISSUE TITLE
Check Request #23 - SprintVersionMismatch, sprint guard against release version

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#40]
Sprint field must match version released. Check query for 7.0.2: https://issues.jboss.org/issues/?filter=12327775

**Comment by rpelisse** [comment]
[Implemented](https://github.com/jboss-set/bug-clerk/commit/ef32f7c24f774b21c17b4411416e811bcf475b16) and will be release in 0.9.0. It does need https://github.com/jboss-set/aphrodite/pull/107 to be merge first.
