### ISSUE TITLE
Check Request #24 - Fix version and Sprint must match between siblings(Upgrade-component fixes)

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#41]
If upgrade JIRA is in sprint X, for version X.x, same must apply to linked issues with category "incorporates" from upgrade JIRA.

**Comment by rpelisse** [comment]
Can you link to some example issues ? (a "good one" and a "bad one").

Also I assume that this check can NOT be used if there is not sprint associated to the issue (like for [JBEAP-5865](https://issues.jboss.org/browse/JBEAP-5865))

**Comment by baranowb** [comment]
Upgrade: sprint 7.0.1, fix version 7.0.1.CR2
Children: Sprint 7.0.1, fix version [7.0.1.C1, 7.0.1.CR2,....,7.0.1.GA)

**Comment by rpelisse** [comment]
[Implemented](https://github.com/jboss-set/bug-clerk/commit/26aed7c909e7961b7cd40497f24c4d653cd12e7b) and released with [Bugclerk 0.9.0.Final](https://github.com/jboss-set/bug-clerk/releases/tag/bugclerk-0.9.0.Final).
