### ISSUE TITLE
Fix Version white list

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#45]
Provide white list for users that "CAN" alter fix version without being annoyed. This is kind of a feature to gently phase out folks from abuse of "Fix Version" field. Basically, if UID is not on the white list, bugclerk should add comment to issue and send warning to jboss-set ?

**Comment by baranowb** [comment]
Connected/Blocked by: https://github.com/jboss-set/bug-clerk/issues/44

**Comment by rpelisse** [comment]
@baranowb We need to drill down on this idea. Bugclerk is right now stateless, it has no database or data file, just (rather static) data file. How do and where do we set up this list of users ? Best would, at first glance, to load it from an external source. Could you rely on a LDAP group ? If so we need to have either an OpenLDAP integration or maybe have a separate tool serving the result as ReST to Bugclerk ?

**Comment by rpelisse** [comment]
I'm going to close this issue because we are still nowhere to find how the white list can be defined.
