### ISSUE TITLE
Support more levels of severity

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#51]
When reporting a violation, Bugclerk should have a more fine grained levels of Severity:

- GREEN, // Severity Level 1, Everything is fine. CP Process is moving forward as planned with no visible obstacles.
- Yellow_GREEN, // Severity Level 2, attention is needed, forward progress can be made.
- YELLOW, // Severity Level 3, A pending condition to Triage.
- ORANGE // Severity Level 4, attention is needed until progress can no longer be made.
- RED; // Severity Level 5, An immediate call to Triage.

**Comment by rpelisse** [comment]
And refactor Level to Severity

**Comment by wolfc** [comment]
Leave colors to the signals. :)

So rather: Trivial, Minor, Major, Critical, Blocker.

The signal would be a call to action, which is derived from the severity of all the violations found on an issue.

**Comment by rpelisse** [comment]
Yes I will - so I will just refactor Level into a new enum with Trivial, Minor, Major, Critical, Blocker.

**Comment by rpelisse** [comment]
Implemented in [commit 7e1ec5dc8d73f5c8df1d2f34229408029f38c232](https://github.com/jboss-set/bug-clerk/commit/7e1ec5dc8d73f5c8df1d2f34229408029f38c232)
