### ISSUE TITLE
Check Request #27 - Ensure upstream issue has the downstream_dependency

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#54]
Upstream issue of JBEAP issue should have a label 'downstream_dependency' to ensure we can keep track of them during releases. 

(note: ultimately, payload-viewer should be able to display their link next to the JBEAP issue)

**Comment by rpelisse** [comment]
AFAIU, there is no handling of [Jira labels in Aphrodite](https://github.com/jboss-set/aphrodite/blob/master/jira/src/main/java/org/jboss/set/aphrodite/issue/trackers/jira/IssueWrapper.java#L132), so I'll need to add support for that. I don't want to delay 0.10.0 release for this, so this issue won't be part of this release.

**Comment by MMarus** [comment]
@MMarus remove/change the usage of SimpleContainer after https://github.com/jboss-set/aphrodite/pull/135 is merged.

**Comment by MMarus** [comment]
Added the usage of a SimpleContainer.

**Comment by rpelisse** [comment]
A [check](https://github.com/jboss-set/bug-clerk/commit/40450b9123180f0f21adc1abd4ae80ba756eb174) has been added to implement this, and it will be released with 1.0.0.
