### ISSUE TITLE
Hang due to JSONException until Jenkins job timeout. 

### ISSUE THREAD

**Issue by soul2zimate** [jboss-set/bug-clerk#56]
Recent bugclerk runs for jira failed due to JSONException, it seems that Jira sometimes can not return good formatted JSONObject in its response as builds in yesterday are good.

Jenkins job log https://thunder.sin2.redhat.com/jenkins/job/bugclerk-reports-jira-eap70z-unresolved/7512/console

The job is aborted until it's timeout set in Jenkins, But I think it should have some timeout value in BugClerk, so it can actively cancel it in such case. 

Low priority. As Jenkins can kill it at 10 mins timeout.

**Comment by rpelisse** [comment]
@MMarus I think you can take a look at this, and come up with a proposal change. it will be a but difficult to test, but maybe you can set up a local http server (apache, httpd) with a dummy, JIRA look-like Rest API that just hangs ?

**Comment by rpelisse** [comment]
Implemented by https://github.com/jboss-set/bug-clerk/commit/e48f81d6e687add5de6e5e6baaaae4486542cd6d, and will be released with 1.0.0.
