### ISSUE TITLE
Check Request #28 - Ensure URLs in the PR field points to PR

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#57]
Anything can be put into a PR fields ! Better checks that

**Comment by rpelisse** [comment]
@MMarus That should be also right up your alley. It's actually pretty simple to implement: retrieve the URL field values, split by ',' if any, and try to turn each part into URL. Maybe also checks they all points to the github server and that the path contains '/pull'

**Comment by MMarus** [comment]
Jira validates if the field  "Git Pull Request" contains URLs.

**Comment by rpelisse** [comment]
As discussed by chat, then the check should verify, as much as possible, that the URL points to a pull request, not just a valid domain name.

**Comment by rpelisse** [comment]
Obviously, as there is a chance for false+ this checks should be log as Warning (not Error) - at least for the first version released.

**Comment by rpelisse** [comment]
This [check](https://github.com/jboss-set/bug-clerk/commit/a0a29ffed0c8013b319a6b9397a401394e1c2e79) has been implemented and will be released with 1.0.0.
