### ISSUE TITLE
Check Request #31: A "component upgrade" issue is attached to the JBEAP issues associated to resolved issue with Fix Version.

### ISSUE THREAD

**Issue by MMarus** [jboss-set/bug-clerk#62]
Check if dependency of a resolved JBEAP issue is being associated to a Resolved issue with a Fix Version , a "component upgrade" issue should be attached to the JBEAP issue.

**Comment by rpelisse** [comment]
Implemented by [commit b24517fa112....](https://github.com/jboss-set/bug-clerk/commit/b24517fa112e27fba71fc30914bd432bca167516) and will be released with [1.0.1](https://github.com/jboss-set/bug-clerk/milestone/4).
