### ISSUE TITLE
Check upgrade JIRAs for Sprint/Stream version discrepencies

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#64]
Mildly related to: https://github.com/jboss-set/bug-clerk/issues/44

Example:
https://issues.jboss.org/browse/JBEAP-5706

Case:
JIRA has been bumped to 7.0.8
Upgrade JIRA is in 7.0.7 and has 7.0.7 sprint.

**Comment by rpelisse** [comment]
This checks has been [implemented](https://github.com/jboss-set/bug-clerk/commit/284a99869eac9da401d27a4816850e919cc7eeee) and will be released in 1.0.0.
