### ISSUE TITLE
Check Request #32 - All issues on payload should have 3 acks

### ISSUE THREAD

**Issue by spyrkob** [jboss-set/bug-clerk#74]
SA CRE: https://docs.google.com/document/d/1n-SsbBs9-9PNGbptnzcwqV6PGcat_Cyh5tu4QSnwPXY/edit

Checks: 
1) All issues on payload should have 3 acks
2) Only issues with QA ack can be worked on

**Comment by rpelisse** [comment]
"2. Only issues with QA ack can be worked on" has been filed into a separate issue ([Check Request #33](https://github.com/jboss-set/bug-clerk/issues/76)) and [merged into the code base](https://github.com/jboss-set/bug-clerk/commit/1b19552d637606e73547e0822552db0dadb1b978).

**Comment by rpelisse** [comment]
"1. All issues on payload should have 3 acks" have been filed under it owns issue ([Check Request #32](https://github.com/jboss-set/bug-clerk/issues/75)), thus closing this issue for clarity purpose.

**Comment by spyrkob** [comment]
@rpelisse updated the PR #32 with just the 1st check.

What's the reason for splitting them up btw?

**Comment by rpelisse** [comment]
Granularity - I try to have one issue for one checks and assign an id to the check request. Also, in this case, one of your checks was "ready to be commit" while the other one was not, so it made sense to me to split it.

**Comment by rpelisse** [comment]
@spyrkob btw the new PR still have the same issue. Any issue are going to be tagged as violation, whether or not the issue belong to a payload. We need a way to determine what a payload is (I think we do, i've been planning to look into that for the all week, but I have yet to come around it).

**Comment by spyrkob** [comment]
@rpelisse ah good point. I was looking at it from prbz-overview point of view where issues are pre-filtered as payload, I didn't think about more general case. I'll see if I can improve that.

**Comment by rpelisse** [comment]
@spyrkob cool :) I actually think that PrBz might be able to give us a hint on how to assert if an issue belong to a payload.
