### ISSUE TITLE
Check Request  #36 - Identify JBEAP issue with a PR not matching Target Release

### ISSUE THREAD

**Issue by rpelisse** [jboss-set/bug-clerk#81]
Whenever a PR is attached to an issue that does not target the right maintenance branch for the given Target Release in the JBEAP issue a violation must be noted.

Good candidates for this check are issues linked to https://issues.jboss.org/browse/JBEAP-12932

**Comment by rpelisse** [comment]
@baranowb do you think you will be ready for this one soon ? I would like to release Bugclerk 1.0.1 by the end of the week ;) !

**Comment by baranowb** [comment]
Filled today. It's hacky, I will improve on monday(if it is possible).

**Comment by rpelisse** [comment]
Implemented by [PR90](https://github.com/jboss-set/bug-clerk/pull/90) and will be released with [1.0.1](https://github.com/jboss-set/bug-clerk/milestone/4).
