### ISSUE TITLE
Check Request #37 - Check if stream status match between blocked/incorporated issues and parent.

### ISSUE THREAD

**Issue by baranowb** [jboss-set/bug-clerk#83]
https://github.com/jboss-set/bug-clerk/pull/84

**Comment by rpelisse** [comment]
@baranowb are you working on this one ? Do you think you will get it done anytime soon ? (ie should I add it to the payload of 1.0.1 ?)

**Comment by baranowb** [comment]
https://github.com/jboss-set/bug-clerk/pull/95/

**Comment by rpelisse** [comment]
Implemented by [PR95](https://github.com/jboss-set/bug-clerk/pull/95) and will be released in [1.0.1](https://github.com/jboss-set/bug-clerk/milestone/4).
